# Site settings
title: "Mike + Suz"
description: |
    We're gettin Married! 
    Friday Jan 20th 2023

owner: Michael Cueno
first_published: 2021
email: krunocrew@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.mikeandsuz.com" # the base hostname & protocol for your site

# Google analytics
google_analytics: ""

social:
  email: krunocrew@gmail.com
#  github: https://github.com/michaelcueno/mikeandsuz.com

# Build settings
markdown: kramdown
